#!/bin/bash
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th0_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th5_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th10_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th15_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th20_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th25_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th30_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th35_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th40_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th45_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th50_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th55_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th60_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th65_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th70_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th75_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th80_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th85_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th90_burn.card.out
python mcnpx_burnup.content_general.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/burn.card/15.00mm_pitch/dt50/2000D/fuel.oxide_th95_burn.card.out
