#!/bin/bash
python mcnpx_burn.radionuclide.content.py fuel.oxide_th0.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th5.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th10.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th15.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th20.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th25.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th30.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th35.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th40.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th45.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th50.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th55.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th60.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th65.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th70.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th75.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th80.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th85.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th90.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th95.inp.o 94239
python mcnpx_burn.radionuclide.content.py fuel.oxide_th0.inp.o 92233 
python mcnpx_burn.radionuclide.content.py fuel.oxide_th5.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th10.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th15.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th20.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th25.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th30.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th35.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th40.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th45.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th50.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th55.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th60.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th65.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th70.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th75.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th80.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th85.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th90.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th95.inp.o 92233
python mcnpx_burn.radionuclide.content.py fuel.oxide_th0.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th5.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th10.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th15.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th20.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th25.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th30.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th35.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th40.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th45.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th50.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th55.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th60.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th65.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th70.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th75.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th80.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th85.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th90.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th95.inp.o 94238
python mcnpx_burn.radionuclide.content.py fuel.oxide_th0.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th5.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th10.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th15.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th20.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th25.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th30.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th35.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th40.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th45.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th50.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th55.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th60.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th65.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th70.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th75.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th80.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th85.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th90.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th95.inp.o 94240
python mcnpx_burn.radionuclide.content.py fuel.oxide_th0.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th5.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th10.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th15.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th20.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th25.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th30.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th35.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th40.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th45.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th50.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th55.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th60.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th65.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th70.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th75.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th80.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th85.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th90.inp.o 94242
python mcnpx_burn.radionuclide.content.py fuel.oxide_th95.inp.o 94242
