#!/bin/bash
mv mcnpx_radionuclide.content_interpolate.py 92233/
cd 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th0_radionuclide.content.out 92233 
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th5_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th10_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th15_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th20_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th25_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th30_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th35_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th40_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th45_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th50_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th55_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th60_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th65_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th70_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th75_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th80_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th85_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th90_radionuclide.content.out 92233
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th95_radionuclide.content.out 92233
mv mcnpx_radionuclide.content_interpolate.py ../94238/
cd ../94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th0_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th5_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th10_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th15_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th20_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th25_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th30_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th35_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th40_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th45_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th50_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th55_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th60_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th65_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th70_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th75_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th80_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th85_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th90_radionuclide.content.out 94238
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th95_radionuclide.content.out 94238
mv mcnpx_radionuclide.content_interpolate.py ../94239/
cd ../94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th0_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th5_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th10_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th15_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th20_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th25_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th30_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th35_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th40_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th45_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th50_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th55_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th60_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th65_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th70_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th75_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th80_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th85_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th90_radionuclide.content.out 94239
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th95_radionuclide.content.out 94239
mv mcnpx_radionuclide.content_interpolate.py ../94240/
cd ../94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th0_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th5_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th10_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th15_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th20_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th25_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th30_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th35_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th40_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th45_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th50_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th55_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th60_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th65_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th70_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th75_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th80_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th85_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th90_radionuclide.content.out 94240
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th95_radionuclide.content.out 94240
mv mcnpx_radionuclide.content_interpolate.py ../94242/
cd ../94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th0_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th5_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th10_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th15_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th20_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th25_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th30_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th35_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th40_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th45_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th50_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th55_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th60_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th65_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th70_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th75_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th80_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th85_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th90_radionuclide.content.out 94242
python mcnpx_radionuclide.content_interpolate.py fuel.oxide_th95_radionuclide.content.out 94242
