#!/bin/bash
python /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/src/mcnpx_insert.column.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/92233/92233.mass_interpolated.out /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/lib/insert.column_th.content.inp
mv *.out /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/92233/
python /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/src/mcnpx_insert.column.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94238/94238.mass_interpolated.out /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/lib/insert.column_th.content.inp
mv *.out /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94238/
python /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/src/mcnpx_insert.column.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94239/94239.mass_interpolated.out /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/lib/insert.column_th.content.inp
mv *.out /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94239/
python /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/src/mcnpx_insert.column.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94240/94240.mass_interpolated.out /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/lib/insert.column_th.content.inp
mv *.out /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94240/
python /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/src/mcnpx_insert.column.py /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94242/94242.mass_interpolated.out /media/sf_home/usr/borrelli/scripts/mcnpx.scripts/lib/insert.column_th.content.inp
mv *.out /media/sf_home/usr/borrelli/mcnpx.decks/thorium.uranium.fuel/homogeneous.th.u.mixture/output/radionuclide.content/13.2mm_pitch/dt50/2000D/94242/
